### ISSUE TITLE
"starting presentation timestamp" in duration change algorithm text is confusing. Drop "starting".

### ISSUE THREAD

**Issue by tidoust** [w3c/media-source#102]
The [Duration Change](http://w3c.github.io/media-source/#duration-change-algorithm) algorithm no longer links to the [Range Removal](http://w3c.github.io/media-source/#sourcebuffer-range-removal) algorithm (the change was made in response to issues #15 and #26, I think).

The [End of Stream](http://w3c.github.io/media-source/#end-of-stream-algorithm) algorithm tells the user agent to update the duration to the _highest end time reported by the buffered attribute_. The intent seems to be to truncate the duration to the content effectively buffered.

Am I right to assume that the track buffer ranges of a SourceBuffer remain untouched when the duration is truncated? If so, am I right to think that the duration may be set to a much larger value when `endOfStream()` is called as in the example below?

```javascript
// Let's say mediaData holds 10s of media content
var sourceBuffer = mediaSource.addSourceBuffer(mimeType);
sourceBuffer.appendBuffer(mediaData);
sourceBuffer.onupdateend = function () {
  // sourceBuffer.buffered.end(0) should now equal 10

  // Truncating the duration no longer removes any buffered frame,
  // so sourceBuffer.buffered.end(0) should still equal 10 after next line
  mediaSource.duration = 2;

  // End of stream algorithm sets duration to the highest end time reported
  // by the buffered attribute, sourceBuffer.buffered.end(0) in this example
  mediaSource.endOfStream();

  // mediaSource.duration should now equal 10. Is this the intended behavior?
}
```

**Comment by wolenetz** [comment]
I don't think that `endOfStream()` can increase the `duration` attribute of a `MediaSource` object. Note that `appendBuffer(mediaData)` uses the `coded frame processing algorithm`, which increases `duration` if a frame end time (which is a coded frame's presentation timestamp + duration) exceeds `duration`. So, I would expect `mediaSource.duration` to be at least 10 in your example, prior to the attempt to truncate it to 2. Now, since mediaSource.duration = 2 is disallowed if it truncates a buffered range (if it is *below* the highest presentation timestamp in any SourceBuffer for the MediaSource) such that at least 1 whole coded frame's presentation interval would be truncated. In that case, you should get an exception. Note that this is a recent spec change, and as such, is only recently in Chrome, and is behind the --enable-experimental-web-platform-features flag currently. Try a Chrome canary build and let me know if you **don't** receive an exception in your example for the `mediaSource.duration = 2;` line.

**Comment by wolenetz** [comment]
@tidoust please re-open this if you confirm unexpected behavior relative to my comment https://github.com/w3c/media-source/issues/102#issuecomment-231894478. Note that, even in the current MSE spec, implementations are still afforded a little leeway: Suppose the highest presentation timestamp were 1, and that coded frame's duration was 9. This would make duration, at minimum, be 10. Setting duration to 2, then, should **not** give an exception, and some implementations (not Chrome) which cannot render a partial frame, are allowed to (as part of the duration change algorithm) set the duration to the highest buffered end time (which would be 10 in your example), instead of 2.

**Comment by tidoust** [comment]
@wolenetz Thanks for the clarifications.

I suspect I got confused because the spec says "If new duration is less than the highest **starting** presentation timestamp" and I assumed that "starting" meant what the `TimeRanges.start` method would report, and thus that duration truncation within a buffered range was actually authorized.

What does "starting" mean in that sentence? Is it always what the `TimeRanges.end` method returns in particular?

(Note I'll need to update tests in pending pull requests that assume that truncation as suggested above is possible)

**Comment by wolenetz** [comment]
@tidoust The word "starting" in the spec text you quoted in https://github.com/w3c/media-source/issues/102#issuecomment-231983784 is extraneous and confusing. I'll remove it. The highest presentation timestamp has no direct correlation to the beginning of a range in TimeRanges returned by any of the `buffered` attributes except coincidentally that the "highest presentation timestamp" might be for a single-coded-frame in its own TimeRange. A time range can (most commonly) have multiple coded frames, so the "start" and "end" times of a time range are different than what the spec is referring to in the duration change algorithm when it says "If new duration is less than the highest presentation timestamp" (again, I'll remove that confusing "starting"). An app, if it receives exception on attempted duration reduction (due to truncating buffered media), could explicitly remove(attempted new duration, old higher duration or just positive Infinity) and (after updateend) then retry the duration reduction and expect success.

I'll rename this issue to reflect the necessary fix is to remove the word "starting" from that spec text.
