### ISSUE TITLE
Normative reference to High Resolution Time is missing

### ISSUE THREAD

**Issue by tidoust** [w3c/media-source#103]
The `getVideoPlaybackQuality` references `Performance.now()` but the specification does not list the [High Resolution Time](https://www.w3.org/TR/hr-time/) specification in the set of normative references.

**Comment by wolenetz** [comment]
Note, the VideoPlaybackQuality object and the HTMLVideoElement Extensions that use it are marked at risk in the current V1 CR spec.

**Comment by wolenetz** [comment]
@jdsmith3000 @paulbrucecotton @mwatson2 @plehegar Would adding such a normative reference constitute a substantive change? Is https://www.w3.org/TR/hr-time/ ok for use as such a normative reference (it claims it's a working draft, though the wording around Performance.now() seems stable for a long time now, and the 2012 version of the previous HR-Time (https://www.w3.org/TR/2012/REC-hr-time-20121217/) is ancient and points readers "to use High Resolution Time Level 2 (or its successor) instead of this document."

IMHO, it wouldn't be a substantive change, but I thought that I should ask you all given the time frame we're in at the moment. Again, note that VideoPlaybakQuality is at risk in our spec.

**Comment by wolenetz** [comment]
https://github.com/w3c/media-source/pull/112/commits/220048fff108d20a7a4dbc5fa92dd11cd8fc8f28 fixes this.
