### ISSUE TITLE
Consider making MSE attachment asynchronous

### ISSUE THREAD

**Issue by wolenetz** [w3c/media-source#104]
@jdsmith3000, @mwatson2  : what do you think? Is there any real restriction on requiring the attachment be synchronous? Would allowing attachment to be done asynchronously constitute a substantive change?

@foolip This follows our discussions on https://bugs.chromium.org/p/chromium/issues/detail?id=615481#c14

**Comment by wolenetz** [comment]
Note, we already asynchronously notify the app upon attachment completion (via 'sourceopen'), so the app-visible difference of allowing asynchronicity within the attachment steps might be negligible. Currently, Chrome attaches MSE asynchronously.

**Comment by wolenetz** [comment]
@jdsmith3000 @mwatson2 friendly ping :)

**Comment by mwatson2** [comment]
IIUC, the difference is that according to the current description, if you assign a MediaSource URL to the `src` element, then in the next statement you could expect `readyState` to be `open`.

Is the suggestion that we change this so that `readyState` may not have the value `open` until the `sourceopen` event handler ?

If so, it's certainly a substantive change (I would need to check with our player team to be sure this would not break our player).

But it also seems like a completely reasonable change and I doubt very much anyone expects the `readyState` to be `open` before the `sourceopen` event.

**Comment by wolenetz** [comment]
> IIUC, the difference is that according to the current description, if you assign a MediaSource URL to the src element, then in the next statement you could expect readyState to be open.

Actually, we are already asynchronous there, too, IIUC. The resource fetch algorithm (which our MSE attachment algorithm modifies to include the MSE readyState transition to 'open', among other things) is scheduled by the resource selection algortihm to run in parallel with some of the latter steps of the resource selection algorithm. But even before that parallelism, the resource selection algorithm's step 4 does: "in parallel await a stable state, allowing the task that invoked this algorithm to continue."

This awaiting of a stable state means that MSE readyState transition to 'open' cannot occur prior to the the next line of JS after setting mediaElement.src=MSEobjectURL.

> Is the suggestion that we change this so that readyState may not have the value open until the sourceopen event handler ?

Certainly not. Though readyState will not be open for some period of the time between start of resource selection algorithm+fetch algorithm. But it should definitely be set open prior to the "queue a task to fire a simple event named sourceopen" step of the attachment (which is current MSE spec text).

Re-reading this in the context of HTML51, I'm uncertain now that this is really an issue: Since the resource fetch algorithm is already running, in parallel, after the resource selection algorithm awaited a stable state, then isn't MSE attachment already effectively asynchronous? @foolip -- I think we might have missed this during discussion on https://crbug.com/615481, unless I'm mistaken.

**Comment by foolip** [comment]
Yeah, I didn't pay attention to the fact that this was after "End the synchronous section, continuing the remaining steps in parallel." That means that the timing can be anything, but it actually seems slightly wrong to me. Things that are "in parallel" could be in another thread or process, so it's weird that "Remove all media-resource-specific text tracks from the media element's list of pending text tracks, if any." and poking at `networkState` is in the resource fetch algorithm. (That should probably  @domenic, would you agree? If so I should file an issue.

For MSE, I think it probably makes most sense to say that resource fetch algorithm has certain changes to its interpretation, and to separately define the timing of the thing that should queue a task to perform steps 1-3 of the otherwise branch in http://w3c.github.io/media-source/#mediasource-attach. And I guess that time is when the MediaSource object internally has set up a decoding pipeline and is ready for action?

**Comment by mwatson2** [comment]
@wolenetz Ok, I'm convinced this is an editorial change, since the steps are already "in parallel".

What I meant was that the _page_ could not _assume_ that `readyState` would be `open` before the execution of the `sourceopen` event handler.

**Comment by wolenetz** [comment]
On Tue, Aug 2, 2016 at 11:31 AM, mwatson2 <notifications@github.com> wrote:

> What I meant was that the *page* could not *assume* that readyState would
> be open before the execution of the sourceopen event handler.
>

Correct, this is the case today already, given we're already running the
attachment steps in parallel after stable state was achieved. But
certainly, at time of handling 'sourceopen', unless there has been some
intervening action to further transition the SourceBuffer's `readyState`
(like the app winning a parallel race with "endOfStream()"), it should be
open.

**Comment by foolip** [comment]
If you queue a task to perform steps 1-3 (and drop "queue a task" from step 3), you would actually guarantee that the `MediaSource` object's `readyState` is "open" when the `sourceopen` event is fired. (But if the thing that underlies the `MediaSource` object is on another thread or process, that apparent simplicity might still just be a lie.)

**Comment by wolenetz** [comment]
Looks like V1Editorial, at most, for MSE. Would a non-normative note in MSE explaining that the transition to 'open' as part of attachment is asynchronous, after a stable state has been achieved, be sufficient? @foolip Would your suggestion in https://github.com/w3c/media-source/issues/104#issuecomment-237036062 require implementation changes (IOW, is it substantive) vs a non-normative note?

**Comment by wolenetz** [comment]
PR #146
