### ISSUE TITLE
Unecessary argument provided to Append Error Algorithm

### ISSUE THREAD

**Issue by jyavenard** [w3c/media-source#159]
https://w3c.github.io/media-source/index.html#sourcebuffer-append-error

Set 5 states:
"If decode error is true, then run the end of stream algorithm with the error parameter set to "decode"."

the Append Error Algorithm is always called with the decode error parameter set to true.

Step 5 should be removed and replace the nine instances stating "run the append error algorithm with the decode error parameter set to true" (every instance referring to the append error algorithm) with "run the append error algorithm"

**Comment by wolenetz** [comment]
That's true. The (currently removed) appendStream had a case which IIRC
exercised the append error algorithm differently.

This looks editorial in nature, not blocking v1 if it doesn't get fixed.

Thanks for reporting this issue.

**Comment by wolenetz** [comment]
@jdsmith3000 @mwatson2 We currently have some redundant verbiage in the spec: since we've removed appendStream(), the error parameter to the append error algorithm is now always true.

@plehegar @paulbrucecotton: Would fixing an editorial-only issue like this require both regeneration of the PR spec, as well as re-requesting CfC? Please help us understand if we need to just punt this to VNext.

**Comment by paulbrucecotton** [comment]
I believe this change can be made editorially after the CfC closes but BEFORE we sent the transition request.

**Comment by jdsmith3000** [comment]
I agree this should be corrected for V1 if at all possible and is completely editorial.
