### ISSUE TITLE
Some of the attributes returning TimeRanges objects seem to return a new object each time the getter is invoked

### ISSUE THREAD

**Issue by wolenetz** [w3c/media-source#16]
Migrated from w3c bugzilla tracker. For history prior to migration, please see:
https://www.w3.org/Bugs/Public/show_bug.cgi?id=27790

**Comment by wolenetz** [comment]
Specifically, we need input from Jean-Yves Avenard on this (and we need to find the right GH account to ping to get that input).

**Comment by bbcrddave** [comment]
@jyavenard

**Comment by jdsmith3000** [comment]
We have an existing commit on this that attempts to re-use sourceBuffer objects if the content hasn't changed, but that behavior specifically does not match that of HTMLMediaElements.  I believe we should consider reverting the commit and closing this issue won't fix.

**Comment by wolenetz** [comment]
I'll prepare a PR shortly with non-normative note indicating the potentially ambiguous text "does not mean" what @jyavenard interpreted in original bug's comment 14.

**Comment by jyavenard** [comment]
Sorry for the delay in responding.

Let me first say that Firefox/Gecko has a change pending (https://bugzilla.mozilla.org/show_bug.cgi?id=1150305) that implements sourcebuffer.buffered as describe in that bug: we return the same TimeRange object if the buffered range hasn't change since it was last queried ; otherwise it returns a new object.
It should be committed in gecko's tree shortly.

Upon further discussion with some colleagues, I believe the text as it is, is okay.

(The source of my confusion is likely because I'm a C++ developer and I distinguish the concept of returning an object by value or by reference ; while JS always mean by reference)

**Comment by wolenetz** [comment]
@jyavenard, thanks for responding. Based on your response, I believe closing this issue as wontfix is the correct action.

**Comment by wolenetz** [comment]
Since the original bugzilla bug was fixed by a commit and the subsequent discussion on that same bug and continued into this GitHub issue was around further improving clarity (which was determined unnecessary in recent comments here), I'm removing the "wontfix" and just closing the issue.

**Comment by jdsmith3000** [comment]
I agree with doing this.
