### ISSUE TITLE
Should the media element load algorithm trigger detaching from a media element?

### ISSUE THREAD

**Issue by wolenetz** [w3c/media-source#17]
Migrated from w3c bugzilla tracker. For history prior to migration, please see:
https://www.w3.org/Bugs/Public/show_bug.cgi?id=27843

It was previously assigned to Adrian Bateman. Editors will sync soon to determine who to take this bug.

**Comment by jdsmith3000** [comment]
The load method does not seem applicable to MSE sourceBuffers, since the Media Element is not doing the media transfers.  That responsibility belongs to the website.  We might want to consider a comment that says load is either a no-op under MSE or perhaps throwing an exception.

**Comment by foolip** [comment]
Calling `load()` doesn't imply that the media element will start a network request or anything like that, it's just a way to reset some state and restart the resource selection algorithm, which may end up picking an object URL that corresponds to a `MediaSource` object, or not.

The problem is that the MSE spec has hooked some behavior into transitions of `networkState` to `NETWORK_EMPTY`, but it doesn't cover `load()` when it really seems like it should.

**Comment by jdsmith3000** [comment]
@foolip It appears to me that `load()` puts the media element into a unintialized state consistent with `NETWORK_EMPTY`, and aligns with the MSE language today.  Do you believe that `load()` should be explicitly referenced in MSE as well as a trigger for detaching from the Media Element?

**Comment by foolip** [comment]
You are right, it is consistent with the definition of `NETWORK_EMPTY`. However, the way the spec is written, the value of `networkState` is not derived from these definitions in every moment, but rather the `networkState` attribute is explicitly updated at various points. (Making it interoperable would otherwise be very hard.) When the `load()` method is called, it ends with invoking the resource selection algorithm, and that will set `networkState` to `NETWORK_NO_SOURCE`. As far as I can see, `networkState` does not necessarily pass through `NETWORK_EMPTY` in this scenario.

I think that this and issue #18 would best be solved with an explicit hook in the media element load algorithm, right after "If a fetching process is in progress for the media element, the user agent should stop it," which most closely corresponds to where one would destroy the backend. Either the MSE spec can define an algorithm that the HTML spec calls or (more cleanly) the HTML spec can define a callback that other specs may register for. Then it ought not be necessary to tie the detach steps to `NETWORK_EMPTY` at all.

**Comment by wolenetz** [comment]
Thanks @foolip. We'll likely have the MSE spec define an algorithm that the HTML spec calls, so that in short term we don't block MSE on HTML spec change (both can and should change).

**Comment by foolip** [comment]
That sounds good. If you define the algorithm and (separately) keep the existing `NETWORK_EMPTY` condition to invoke it, I can invoke it from HTML, and then you can remove the `NETWORK_EMPTY` hook entirely. Just poke me when that algorithm exists with a stable ID.

**Comment by jdsmith3000** [comment]
Would anything differ in this algorithm from the "Detaching from a media element" algorithm that currently exists?  I believe it's steps are required, and the only difference would be that it's initiated on HTMLMediaElement load.  If so, we might modify the algorithm intro to include load() as another initiator.  The rest of the intro text appears applicable:

> The following steps are run in any case where the media element is going to transition to NETWORK_EMPTY and queue a task to fire a simple event named emptied at the media element. These steps must be run right before the transition.

**Comment by foolip** [comment]
That algorithm looks right, but ideally it should be on a form similar to https://w3c.github.io/webappsec-csp/#html-integration with hooks explicitly intended for such integration and not used internally by the MSE spec.

Something like this in MSE, where the term is #detach-media-source or similar:

> To **detach** a *media source* from a *media element*, run these steps:
> 1. Set the `readyState` attribute to `"closed"`.
> 2. ...

In HTML we could then say as part of the media element load algorithm:

> **Detach** the attached *media source*, if any, from the *media element*.

And similar for the other cases where implementations clear the media source, which seems to include at least the `MEDIA_ERR_SRC_NOT_SUPPORTED` error condition in Blink.

WDYT?

**Comment by jdsmith3000** [comment]
@joolip That looks simple enough.  Is the goal to leave the conditions that call **detach** up to other documents?  The existing NETWORK EMPTY trigger is a partial HTML integration condition already.  That suggests removing 2.4.2 in general and adding the general detach steps under a new section 2.5 **Integration with HTML**.  Or the existing 2.4.2 could be recast for external use and made general purpose where it is.  Is there a preference?

I'll do a PR once I hear back.

**Comment by foolip** [comment]
Indeed, the idea is that HTML would say "**Detach** the attached *media source*, if any, from the *media element*" and unless there are MSE-internal reasons for detaching, **detach** would only be called from HTML.

I think that an explicit **Integration with HTML** section sounds good, but the precise name of the section isn't a big deal, as long as the algorithms are defined and there's a non-normative note that says that HTML calls these algorithms from such and such place.

If you prepare a PR with MSE with placeholders for "such and such", I can then prepare an HTML PR that adds those calls and say what "such and such" should be replaced with.

**Comment by jdsmith3000** [comment]
@foolip:  I finally got to this.  It uses the existing _#mediasource-detach_ for your reference.

**Comment by foolip** [comment]
Thanks, I'll take a look!
