### ISSUE TITLE
URL.createObjectURL IDL is wrong (no overload across partial interfaces)

### ISSUE THREAD

**Issue by saschanaz** [w3c/media-source#211]
https://heycam.github.io/webidl/#idl-overloading

>Operations must not be overloaded across interface, partial interface, interface mixin, and partial interface mixin definitions.
>
>For example, the overloads for both f and g are disallowed:
>
>```webidl
>[Exposed=Window]
>interface A {
>  void f();
>};
>
>partial interface A {
>  void f(double x);
>  void g();
>};
>
>partial interface A {
>  void g(DOMString x);
>};
>```

Currently the MSE spec is adding an overload for `URL.createObjectURL` by a partial interface.

```webidl
[Exposed=Window]
partial interface URL {
    static DOMString createObjectURL(MediaSource mediaSource);
};
```

We should probably fix this in the [File API](https://w3c.github.io/FileAPI/#dfn-createObjectURL) spec.

**Comment by wolenetz** [comment]
Follow-up on this in V2 milestone is necessary, since this is the only current way to extend and support MSE REC.

**Comment by saschanaz** [comment]
w3c/FileAPI#103 did the work, MSE can simply remove it.

**Comment by tidoust** [comment]
There are tests on `createObjectURL` under [`wpt/media-source`](https://github.com/web-platform-tests/wpt/tree/master/media-source). They should probably be moved to [`wpt/FileAPI/url`](https://github.com/web-platform-tests/wpt/tree/master/FileAPI/url) afterwards, since they would no longer test normative behavior defined in MSE (at least at first sight).
