### ISSUE TITLE
Spec is ambiguous as to event behavior of an explicit MediaSource duration of +Infinity

### ISSUE THREAD

**Issue by wolenetz** [w3c/media-source#27]
Migrated from w3c bugzilla tracker. For history prior to migration, please see:
https://www.w3.org/Bugs/Public/show_bug.cgi?id=28822

**Comment by jdsmith3000** [comment]
For the purposes of the duration change algorithm, infinity is considered a known value that means a live stream.  We are not aware of any definitions in the MSE spec that state infinity implies an "unknown duration".  That may have existed at some previous point in the spec.

**Comment by jdsmith3000** [comment]
For the purposes of the duration change algorithm, infinity is a known value meaning a live stream.  A duration change event should fire on it.  We don't believe there are conflicting statements in the current spec on this, though there may have been some previously.  We believe this issue is closed.
