### ISSUE TITLE
Move VideoPlaybackQuality object to a separate extension spec

### ISSUE THREAD

**Issue by ddorwin** [w3c/media-source#69]
I propose that we remove the [`VideoPlaybackQuality` object](http://w3c.github.io/media-source/#idl-def-VideoPlaybackQuality) and corresponding `getVideoPlaybackQuality()` [extension](http://w3c.github.io/media-source/#htmlvideoelement-extensions) to the `HTMLVideoElement` element from v1 to be incubated as a separate extension. (Possible outcomes include a separate Playback Performance Extensions spec or integration into to HTML 5.x.)

1. Although this functionality may be useful for adaptive streaming use cases, it is really an independent extension to `HTMLVideoElement` that is orthogonal to MSE [1]. It does not affect the core functionality of MSE and should be supported for all source types (including `.src=` ).

1. There is some question about the best way to provide information about current playback performance to applications. As one example, there is not currently a way for applications to observe changes. This capability would benefit from broader incubation, including from those that did not participate in the MSE & EME TF. If this functionality goes to REC along with the rest of MSE, any future efforts will need to deprecate part of the MSE spec or build around it.

1. One member (`totalFrameDelay`) of this object is already marked At Risk.

Moving this functionality out of the MSE spec should actually simplify the path to PR and REC by reducing the scope of the spec and removing one of the At Risk features.

Note: Moving this functionality to another spec/forum _does not_ affect what browsers implement - only the declared maturity level of the feature. Implementations that have implemented some or all of it may continue to do so, but further incubation and iteration is likely before it becomes a Recommendation. Implementation experience will be valuable input to that process.

Note: We can temporarily move these sections to a separate page within the `media-source` repo to provide an informal reference until we identify a new home.

[1] When this was added to MSE, there was no established or lightweight mechanism for small specs or extensions to existing specs. Since that time, the W3C and even HTML have adopted more iterative processes.

**Comment by mwatson2** [comment]
This has been implemented by at least 3 browsers and we are using it in our production application. Feedback from our client team is that it is working just fine as it is.

I think if there was a better proposal on the table and consensus to move towards that, it would make sense to replace this with that. But we are at square one with any such better proposal. What's in the spec was the subject of extensive discussion. Shouldn't we standardize what we have agreed and what has been implemented ? It doesn't mean we can't make improvements in the future.

**Comment by jdsmith3000** [comment]
I agree with Mark's comments.  There may be some merit in the suggestion, but implementations exist and we don't want to undo them with a late spec change.  I'm going ahead and marking the issue VNext.  If there's a need to review, we can discuss it on the next call.

**Comment by mounirlamouri** [comment]
/CC some Mozilla folks @cpearce @cpeterso @jyavenard

The idea here is not to ask the current implementations to delete there code. Obviously, given that there is a web compatibility issue, this will not happen. We believe that the feature isn't mature enough to go to REC and be fully frozen and we would like to work on this in a different place so we can work on the bigger picture (not MSE-only), improve the API and with a group focused on that particular problem.

We know that there is some interest and there isn't much changes we can do an a spec on its way to REC. Because of this, I would like to propose to move the video palyback quality parts of MSE to [WICG](https://www.w3.org/community/wicg/) so we can work on the feature with better focus and without boundaries. Assuming you guys approve this, I would volunteer to move the spec over a new WICG. The process is fairly lightweight.

**Comment by kentuckyfriedtakahe** [comment]
VideoPlaybackQuality is useful as it is however it could be improved. My impression is that sites aren't aggressive enough about ramping up video quality and I want to provide the right information to make it possible. The problem with using droppedVideoFrames is that it is a failure recovery.

My view is that solving the dynamic predictive case is a necessary and complete solution. I'm interested in experimenting and think that a query like "can I play n times the current rate?" would work.

It would also be useful for the browser to notify the script with "please reduce load" notification. This could be triggered when a video is not visible (off screen, in a background tab, etc) or when the system is under too much load (e.g. CPU is not keeping up with decode or decoding needs to be moved from a hardware resource to a software resource).

**Comment by joeyparrish** [comment]
Right now, Shaka Player uses this API for reporting to the application, but doesn't act on the information at all.  It would be ideal if we had a clear signal for "we need to reduce CPU load".  Right now we play whatever we have bandwidth and keys for.  If we could adapt to resource constraints, that would be a much better user experience.  Right now, extracting that signal from dropped frame count feels too difficult and error-prone, so we have not tried.

**Comment by kentuckyfriedtakahe** [comment]
The "point of order" is that it doesn't need to be part of MSE. Without it, the spec lacks any concept of back pressure and @mwatson2 pointed out that some players currently depend on it. Back pressure is important if you wish to make a hands free player that doesn't offer any kind of resolution/quality override. Although I think hands free operation is important, I don't think VideoPlaybackQuality is part of the MVP (Minimum Viable Product) for the MSE spec. For that reason I agree that decoupling it form the MSE spec makes sense.

**Comment by jdsmith3000** [comment]
Providing a means to measure effective performance at a selected quality level seems like a core feature for MSE.  Without it, we provide a means to dial quality up and down, but leave whether the quality level is rendering adequately as an unanswered question.

The WICB process is lightweight, but doesn't provide a spec we can reference either, correct?

**Comment by ddorwin** [comment]
MSE provides the means "to dynamically construct media streams for &lt;audio&gt; and &lt;video&gt;." Nothing in the spec says how an app should select or construct those streams. In fact, the most common mechanism - bandwidth estimation - is not covered by the MSE spec. Likewise, I don't see why measuring playback quality needs to be covered or specified in the MSE spec. Because neither is core to the spec or its algorithms, we do not need a spec to reference from the MSE spec.

As for providing a means to dial quality up and down based on rendering performance, we have feedback from multiple people that they are concerned that the information currently spec'd is not sufficient or reliable enough to use it to make such decisions.

Separating the quality measurement from the construction of streams will allow allow further experience and iteration on the former without holding up the latter. Given the concerns, it does not make sense to make the former a Recommendation on the same schedule as the rest of MSE.

**Comment by jdsmith3000** [comment]
@adrianba We believe it is best practice to document reality.  If another browser wants to implement this behavior (as several have already), they should not have to figure it out without a spec.  It should be documented.  Writing it into the spec now doesn’t mean we can’t change it or deprecate it in future.

@ddorwin I see mixed feedback above, and at least Netflix reports that they are using the feature as spec'd and believe it is useful.

**Comment by wolenetz** [comment]
Marking V1, this issue needs traction in V1 time-frame.

**Comment by paulbrucecotton** [comment]
Removing this feature is a "substantive change" and would require we republish the MSE CR.  An alternative might be to leave it in the spec and note the current design might be deprecated in the future.  This is much less work especially given we have implementations.

**Comment by steelejoe** [comment]
@jdsmith3000 I am late to comment on this, but I have had confirmation that Adobe is also using this feature with our player library. We are definitely in favor of documenting it.

**Comment by joeyparrish** [comment]
I don't know what the rules are for w3 specs.  Is removing the current version from the MSE spec necessary before it can be developed in another direction in its own spec?

**Comment by paulbrucecotton** [comment]
No.

**Comment by jdsmith3000** [comment]
I know of one other company that reports they are using this feature successfully.  The implementations can remain if we pull the feature from the spec and work it separately, but I still believe the best practice is to keep it publically documented in the V1 spec.

**Comment by paulbrucecotton** [comment]
> An alternative might be to leave it in the spec and note the current design might be deprecated in the future.

I want to repeat my suggestion for clarity.  We can leave the current design in the current spec AND work on an alternative.  If we do this it would probably be best that the current design include some sort of annotation to say the community is investigating an alternate design.

**Comment by wolenetz** [comment]
Per our chat just now @ the editors' f2f, @paulbrucecotton (https://github.com/w3c/media-source/issues/69#issuecomment-219295762) I would like VideoPlaybackQuality, if kept as some note in MSE spec, to be non-normative to MSE implementations.

**Comment by wolenetz** [comment]
Sections 5 and 10 (VideoPlaybackQuality object and the extension to HTMLMediaElement interface of getVideoPlaybackQuality()) should contain the followin proposed *normative* statement from editors sync today (see https://w3c.github.io/html/browsers.html#offline-web-applications for similar w.r.t. appcache in HTML51):

"The following section is OPTIONAL and subject to change. The community is investigating alternate designs for providing feedback on media playback quality."

The "underdefined" bug #76 would become VNext.

**Comment by wolenetz** [comment]
@paulbrucecotton Would the following update to the proposed comment (_italicized_ portions are new) be acceptable?

The following section is OPTIONAL and subject to change _because it is underdefined_. The community is actively investigating alternate designs to provide feedback on media playback quality_, which you can follow along here:  https://wicg.github.io/media-playback-quality/_

**Comment by mwatson2** [comment]
I think 'not sufficiently well-defined for all use-cases' would be more accurate. As I mentioned we are using it and it is working well for our purposes.

**Comment by wolenetz** [comment]
@mwatson2 For your use cases, do you use all of the defined VideoPlaybackQuality object fields? If not, might it be prudent to reduce the MSE spec's (proposed OPTIONAL) version of this object to the set of fields you are using?

**Comment by paulbrucecotton** [comment]
I propose the following text:

"The following section is OPTIONAL.  There are several implementations of the current specification but it is subject to change because some feel it needs further work.  The community is actively investigating alternate designs to provide feedback on media playback quality.  See https://wicg.github.io/media-playback-quality/ ."

**Comment by jdsmith3000** [comment]
@paulbrucecotton The proposed wording looks good to me.

> The following section is OPTIONAL. There are several implementations of the current specification but it is subject to change because some feel it needs further work. The community is actively investigating alternate designs to provide feedback on media playback quality. See https://wicg.github.io/media-playback-quality/ .

@Wolenetz I can create a PR for this today.  Please confirm you aren't working it and I'll re-assign to me.

**Comment by wolenetz** [comment]
@jdsmith3000 go ahead and please produce PR. I'll reassign to you now. I'm reviewing the fix for #78 as well as producing the PR for #5. The latter might not be ready prior to tomorrow's meeting, but is next on my plate to get done before the deadline June 9.

**Comment by jdsmith3000** [comment]
I'm working remotely now and won't do the PR until tomorrow morning.

**Comment by jdsmith3000** [comment]
Closed by merge of pull request #89 via commit https://github.com/w3c/media-source/commit/6a476b073fcaa68e58bed466deb24c717c50370b.

**Comment by wolenetz** [comment]
@mwatson2, please comment on https://github.com/w3c/media-source/issues/69#issuecomment-222220355

We are nearing PR, and this feature is currently marked at risk and OPTIONAL. What we have in the spec seems much like a deprecation message. Why not publish the current VPQ as a separate note and remove it from the MSE spec?

I'm reopening this one, accordingly.

**Comment by paulbrucecotton** [comment]
What does our MSE testing indicate about this feature?
http://w3c.github.io/test-results/media-source/all.html
http://w3c.github.io/test-results/media-source/less-than-2.html
http://w3c.github.io/test-results/media-source/complete-fails.html

**Comment by wolenetz** [comment]
Our testing coverage for VPQ is minimal, and has been so for a long time. I'll have further details posted here on this issue tomorrow.

**Comment by paulbrucecotton** [comment]
>I'll have further details posted here on this issue tomorrow.

@wolenetz : Status?

**Comment by wolenetz** [comment]
My apologies - I was out unexpectedly most of Thursday and all of Friday. I'll update this soon with details this week.

**Comment by wolenetz** [comment]
Our MSE testing (per report provided by @tidoust, which was done with his pending test PRs merged locally IIUC) for VPQ: http://w3c.github.io/test-results/media-source/all.html

Our concerns related to the underspecifation of VPQ in MSE currently are summarized in #76, copied here:
* The spec does not say what to do if values cannot be provided, potentially leading to interop issues and/or authors ignoring them.
 * For example: Firefox and Chrome always report corruptedVideoFrames as 0, meaning a value of 0 is meaningless to authors. If this value can’t be calculated by most implementations, maybe it should be removed from the spec. Otherwise, there should be a specification of how to do feature detection. For example, state that implementations should not expose an attribute it cannot support or otherwise indicate it is invalid (a nullable/optional value?).
  * If the implementations are inaccurate, it may be misleading authors.
* Is there no concern or parallel for corrupted audio decode? (Perhaps this should be a MediaQualityObject.)
 * droppedVideoFrames covers both predecode drop and missing deadline drop:
  * is this distinction relevant to authors, and can all/most implementations cover both types of drops?
  * If not, this value would be unreliable and we need some sort of feature detection.
 * Optionality in whether to report corrupt frames as dropped: This allows implementation flexibility, but should implementations be consistent in reporting?
* In addition to polling, a better MediaPlaybackQuality spec might well include an event or constraint mechanism to notify apps when quality has changed.

Relative to MSE v1 test status:
*  The test suite coverage of VPQ is just:
 * IDL (currently a couple VPQ-related IDL tests have less than 2 passing impls)
 * a couple small tests that only verify that the VPQ object's counters are non-decreasing during playback (and >=0), and the object creation time is sane. If a field isn't supported (e.g., totalFrameDelay), then it shouldn't be present in the object at all. If VPQ isn't supported (e.g., in Chrome without the --enable-experimental-web-platform-features), then support detection is clear. But verifying/verification of *correct*, *interoperable* support for fields in VPQ is the harder part that isn't currently covered: interoperable test media that has corrupted frames, as well as interoperable tests that induce "dropped" frames for reasons like decoder stall, etc, are likely to be very hard to do with the current definitions (and frankly, with the lack of having such detailed interop tests to date for VPQ to help force implementations to align).

Our position (ddorwin@ and myself) has and still is that the VPQ feature doesn't really belong in MSE, that there is a published CR document that current implementors and users of the feature can reference, and that maturing the feature belongs in a separate spec going forward. Baking into the MSE spec an "optional", "will be deprecated in future", feature known to be such at time of trying to enter PR seems premature to me and risks interoperability of the currently underdefined feature going forward.

**Comment by jdsmith3000** [comment]
There's not much new information here though, right?  Interop isn't guaranteed, but we have multiple services using the feature and aren't getting VideoPlaybackQuality bugs from them.  There's a proposed Media Playback Quality spec that looks much like our current draft applied to HTMLVideoElements.  And there's still an argument for documenting what we are shipping, and include some cautionary text so that services are fully informed.  We've got that now:

>VideoPlaybackQuality Object

> The following section is OPTIONAL. There are several implementations of the current specification, but it is subject to change because some feel it needs further work. The community is actively investigating alternate designs to provide feedback on media playback quality. [See Media Playback Quality](https://wicg.github.io/media-playback-quality/).

I really think we should leave this feature in the MSE spec to the extent allowed by test results.  That puts totalFrameDelay at risk.  I believe services use it too, but if Edge alone implements it, there can't be two passing implementations.  Media Playback Quality currently includes totalFrameDelay, so it's not really gone away just yet.

**Comment by plehegar** [comment]
I wrote a short test with a corrupted video (and a non corrupted one):
 http://jay.w3.org/~plehegar/vpq/index.html

Firefox gives up on the video once the corrupted frames are reached, thus no corrupted frames are reported (nor totalVideoFrames). video.ended is false and video.error contains a MediaError. So somehow, despite the fact that the video played some frame, it disappears entirely and it reported that it didn't play any frame at all.

Chrome reports 86 total frames, no corrupted frames. video.ended is false and video.error contains a MediaError. The last display frame is 2.22 (the non corrupted video is 2.29).

Edge reports 88 total frames, no corrupted frames.  video.ended is true and video.error contains no error. The last display frame is 2.2X (last digit is corrupted). It also reports inconsistent totalVideoFrames on the non-corrupted video, without reporting any dropped or corrupted frames.

So, I'm really wondering how services can make use of VPQ today in any sort of way. If someone has a better corrupted video file to test with, I'm happy to try btw.

**Comment by wolenetz** [comment]
VPQ is not core to MSE; it's tangentially related. 3 of the 5 fields currently (as @plehegar demonstrated for corruptedFrames in https://github.com/w3c/media-source/issues/69#issuecomment-237025201, and as test suite results demonstrates for totalFrameDelay) are problematic (reporting incorrectly/inconsistently and with differing behavior across implementations). The OPTIONAL spec text's implementation discrepancies make it clear that VPQ/MPQ needs more work.

Regarding:
> And there's still an argument for documenting what we are shipping,

Per my first paragraph in this response, we are shipping significantly inconsistent implementations, for the subset of UAs that contain implementations. We could just as easily (and, importantly, with clearer intent to fix the inconsistencies by iterating on a more precise spec and implementations and not bake the premature VPQ spec into MSE v1) change the current spec text from:
> VideoPlaybackQuality Object
> The following section is OPTIONAL. There are several implementations of the current specification, but it is subject to change because some feel it needs further work. The community is actively investigating alternate designs to provide feedback on media playback quality. See Media Playback Quality.

to:
1) Drop the VPQ object and fields from the MSE spec, and replace the text above with:
2) "For a preliminary version of the VideoPlaybackQuality object specification, which some implementations try to conform to, please see [link to the MSE CR publication URL (or something similar and persistent)]. The community is actively investigating alternate designs to provide feedback on media playback quality. See Media Playback Quality."

**Comment by jdsmith3000** [comment]
I'm okay with your proposed change to reference a CR (or other persistent draft).  Some slight rewording is proposed below:

1. Remove the current VideoPlayBackObject contents (including Attributes) and replace it with:

> VideoPlaybackObject - REMOVED (or DEPRECATED?)
> Video playback quality has been removed from this specification to allow the feature to mature and to accommodate use beyond Media Source Extensions.  See [Media Playback Quality](https://wicg.github.io/media-playback-quality/).  
Some Media Source Extension implementations may have implemented the draft VideoPlaybackQuality feature.  Please see [Media Source Extensions, Candidate Recommendation](http://www.w3.org/TR/2016/CR-media-source-20160705/) for details.

**Comment by jdsmith3000** [comment]
I believe this change was directly committed.

I've reviewed the change and think it's fine.  The change to moving the legacy feature text to the Appendix makes sense.

**Comment by paulbrucecotton** [comment]
> Please see Media Source Extensions, Candidate Recommendation for details.

Can we change the hyperlink to "[Section 5 of Media Source Extensions Candidate Recommendation](http://www.w3.org/TR/media-source/#videoplaybackquality)"?

Note that this change will need concurrence of the HME WG via a CfC on the handling of all the MSE CR "at risk" features.

/paulc

**Comment by paulbrucecotton** [comment]
@wolenetz and @jdsmith3000   Upon further thought shouldn't Section 5 be maintained in the VNext branch ie should we create the VNext branch BEFORE we make this change?

**Comment by ddorwin** [comment]
@jdsmith3000, it that commit was in @wolenetz's fork. I think he'll make a PR at some point.

The hyperlink to Section 5 should be to the dated CR URL: https://www.w3.org/TR/2016/CR-media-source-20160705/#videoplaybackquality

@paulbrucecotton, the definition of this feature would not be part of the PR or VNext - it will be developed as an independent spec. Thus, we should make this change BEFORE branching.

**Comment by paulbrucecotton** [comment]
>it will be developed as an independent spec

@ddorwin - How was this decision made?

**Comment by jdsmith3000** [comment]
It's not really been made, but a separate spec for [Media Playback Quality](https://wicg.github.io/media-playback-quality/) was submitted by Google into the WICG.  It's modeled after the draft MSE feature.

**Comment by wolenetz** [comment]
@jdsmith3000 @ddorwin, yes I'm iterating in my fork and about to send a PR on this.

**Comment by wolenetz** [comment]
PR #135 is ready for review.
@paulbrucecotton @jdsmith3000  VPQ was described in two sections, so I kept the hyperlink to the entire July 5 CR doc, but mention explicitly the 2 sections in the PR.
