### ISSUE TITLE
Update reference from HTML5.0 to HTML 5.1

### ISSUE THREAD

**Issue by plehegar** [w3c/media-source#78]
Since the timeline of HTML 5.1 is aligned with the timeline of MSE and EME, we could update our references to point HTML 5.1 or directly to http://www.w3.org/TR/html which will always contains whatever the latest version of HTML is.
See
[[
 <arronei> tr/html will point to the latest, tr/html5 points to 5.0, tr/html51 points to html 5.1
]]
https://www.w3.org/2016/05/10-html-editors-minutes.html#item04

**Comment by plehegar** [comment]
I'm happy btw to submit a PR for this one.

**Comment by paulbrucecotton** [comment]
I believe we added the informative reference to HTML5.1 when resolving [ISSUE-17](https://github.com/w3c/media-source/issues/17l) and [ISSUE-18](https://github.com/w3c/media-source/issues/18).  Given that we now know the HTML5.1 schedule I am okay with removing the informative references and changing our normative reference to HTML5.1 or to the latest version of HTML.

**Comment by paulbrucecotton** [comment]
I recommend we open a similar issue on the EME spec to change its normative reference to HTML to be the same as is used for MSE when this issue is resolved.

Currently EME uses the following normative reference:

[HTML5]

Ian Hickson; Robin Berjon; Steve Faulkner; Travis Leithead; Erika Doyle Navara; Edward O'Connor; Silvia Pfeiffer. W3C. [HTML5](http://www.w3.org/TR/html5/). 28 October 2014. W3C Recommendation. URL: http://www.w3.org/TR/html5/

**Comment by wolenetz** [comment]
@plehegar @jdsmith3000 Per editors meeting, this is V1.

**Comment by wolenetz** [comment]
Pending @plehegar. Do you have an ETA for PR?

**Comment by plehegar** [comment]
Working on it as I write. ETA is today.

**Comment by plehegar** [comment]
See https://github.com/w3c/media-source/pull/84

**Comment by wolenetz** [comment]
Fixed by https://github.com/w3c/media-source/commit/1b026bba548f282c63ae9b6bb619792a9b03b3b9
Thanks for doing the bulk of this, @plehegar !
