### ISSUE TITLE
"effective script origin" is no longer a thing

### ISSUE THREAD

**Issue by annevk** [w3c/media-source#93]
And it seems very strange to use that anyway, as it only matters for some legacy `document.domain` cases.

**Comment by wolenetz** [comment]
Interesting. @annevk, this is a little new to me, so please help me understand what the right thing to do in MSE spec would be to retain CORS protection (and similarly, since MSE doesn't directly support mixed content, to retain protection against MIX until a mechanism is described to support that in MSE).

**Comment by wolenetz** [comment]
Also, it seems to me this is a V1Editorial. @jdsmith3000 @mwatson2 @annevk  please indicate otherwise ASAP if you believe this is a substantive change (see our recent [CfC](https://www.google.com/url?q=https%3A%2F%2Flists.w3.org%2FArchives%2FPublic%2Fpublic-html-media%2F2016Jun%2F0019.html&sa=D&sntz=1&usg=AFQjCNG-Tu8PLycuneJj0dGIgbmu1eMhUw) and the timeline it references, which means such substantive change would need to go into VNext.

@paulbrucecotton FYI

**Comment by annevk** [comment]
I think you just want to grab origin from somewhere. Not sure if substantive, it’s wrong though…

**Comment by mwatson2** [comment]
How about the "origin of the relevant settings object" (with respect to the call to createObjectUrl) ?

**Comment by annevk** [comment]
Doesn't the File API specification define the origin here for you? It defines the registry for identifier-to-object mappings, including their origin, no?

**Comment by annevk** [comment]
("Relevant settings object" used like that doesn't make much sense. You can only use that in reference to an object.)

**Comment by mwatson2** [comment]
The [latest ED of the File API](https://w3c.github.io/FileAPI/#originOfBlobURL) says "the effective script origin of the incumbant settings object". So, wrong on two fronts I believe.

I meant the relevant settings object of whatever `this` was for the call to `createObjectUrl` (i.e. the `MediaSource` object).

**Comment by annevk** [comment]
Presumably this would be the URL since that's where createObjectURL is invoked upon as static...

**Comment by mwatson2** [comment]
Yes, my mistake, it would be the relevant settings object of `window.URL` in the normal case, not the `MediaSource` object.

**Comment by mwatson2** [comment]
PR #128
